### ISSUE TITLE
Current status of this crate

### ISSUE THREAD

**Issue by vgarleanu** [diesel-rs/diesel_full_text_search#11]
HI, What is the current status of this crate? and is it abandoned?

**Comment by weiznich** [comment]
I would say it is passively maintained, in such sense that the current implementation works but there is currently no undergoing work to add new features.

**Comment by vgarleanu** [comment]
Thanks for the reply. One last question, are there any docs and examples
available. I can't seem to figure out how to use this crate.

**Comment by weiznich** [comment]
There are currently no docs or examples available. Maybe look at the `crates.io` source code they use this crate.

**Comment by vgarleanu** [comment]
Great. Thanks a lot.
