### ISSUE TITLE
Diesel Migration does not properly import diesel full text search

### ISSUE THREAD

**Issue by Jackbaude** [diesel-rs/diesel_full_text_search#26]
When I run `diesel migration run` with the following SQL, the Tsvector is not properly imported and initialized. 
```SQL
ALTER TABLE articles ADD COLUMN text_searchable_article_col tsvector NOT NULL;

UPDATE articles SET text_searchable_article_col = to_tsvector('english', title || ' ' || description);

CREATE INDEX textsearch_idx ON articles USING GIN (text_searchable_article_col);

CREATE TRIGGER tsvectorupdateproducts BEFORE INSERT OR UPDATE
ON articles FOR EACH ROW EXECUTE PROCEDURE
tsvector_update_trigger(text_searchable_article_col,'pg_catalog.english', title, description);
```

Results in the schema..

```rust
      table! {
          use diesel::sql_types::*;
          /// Representation of the `articles` table.
          ///
          /// (Automatically generated by Diesel.)
          articles (urn_title) {

...
          /// The `text_searchable_article_col` column of the `articles` table.
          ///
          /// Its SQL type is `Tsvector`.
          ///
          /// (Automatically generated by Diesel.)
          text_searchable_article_col -> Tsvector,
      }
```

I don't know if this is a feature that has not yet been made, or a bug, but it is definitely something that I think that should be added, so that everytime I run the migration I don't have to manually do this.

**Comment by weiznich** [comment]
This is expected behavior. You need to tell diesel cli that you use custom types. See [the corresponding guide for details](http://diesel.rs/guides/configuring-diesel-cli/)

**Comment by Jackbaude** [comment]
Thank you! But is there a reason that Diesel is adding the column to the schema with a lowercase 'v' in `Tsvector` instead of `TsVector`?
```rust
/// Its SQL type is `Tsvector`.
///
/// (Automatically generated by Diesel.)
text_searchable_article_col -> Tsvector,
```

**Comment by Jackbaude** [comment]
> This is expected behavior. You need to tell diesel cli that you use custom types. See [the corresponding guide for details](http://diesel.rs/guides/configuring-diesel-cli/)

Thanks this worked great, I should have read the docs closer my apologies. However, I'm still not quite I understand if I am supposed to be doing something with the `TsVector` type because diesel is setting my `text_searchable_article_col` column as a `Tsvector` type instead of a `TsVector` type

**Comment by weiznich** [comment]
@Jackbaude That's then #8.

**Comment by Jackbaude** [comment]
Ah, that PR was recently and is not in v1.0.1
