### ISSUE TITLE
I upgraded from an older version and can't get it to build

### ISSUE THREAD

**Issue by freiguy1** [diesel-rs/diesel_full_text_search#3]
I've been working for a couple hours to try to figure this out. It used to work with an older version, I think like 0.8. 

My code:

```rust
let query_items: Vec<&str> = query.trim().split_whitespace().collect();
let query = query_items.join(" & ");
let tsquery = to_tsquery(query);
let tsvector = to_tsvector("'english', name || ' ' || organization");
let result = try!(league::table.filter(&tsvector.matches(&tsquery)).load::<LeagueDao>(self.conn));
Ok(result)
```

And the first part of the not-so-obvious error

```
error[E0277]: the trait bound `diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>: diesel::Expression` is not satisfied
  --> src/repo/league/league.rs:80:41
   |
80 |         let result = try!(league::table.filter(&tsvector.matches(&tsquery)).load::<LeagueDao>(self.conn));
   |                                         ^^^^^^ the trait `diesel::Expression` is not implemented for `diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `&diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>`
   = note: required because of the requirements on the impl of `diesel::query_dsl::filter_dsl::FilterDsl<&diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>>` for `diesel::query_builder::SelectStatement<schema::league::table>`

```

**Comment by sgrif** [comment]
You have two versions of Diesel in your project. You can confirm this by looking in your Cargo.lock and noting that Diesel appears twice. You can fix it by running `cargo update`.

**Comment by jiangxiaoqiang** [comment]
> I've been working for a couple hours to try to figure this out. It used to work with an older version, I think like 0.8.
> 
> My code:
> 
> ```rust
> let query_items: Vec<&str> = query.trim().split_whitespace().collect();
> let query = query_items.join(" & ");
> let tsquery = to_tsquery(query);
> let tsvector = to_tsvector("'english', name || ' ' || organization");
> let result = try!(league::table.filter(&tsvector.matches(&tsquery)).load::<LeagueDao>(self.conn));
> Ok(result)
> ```
> 
> And the first part of the not-so-obvious error
> 
> ```
> error[E0277]: the trait bound `diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>: diesel::Expression` is not satisfied
>   --> src/repo/league/league.rs:80:41
>    |
> 80 |         let result = try!(league::table.filter(&tsvector.matches(&tsquery)).load::<LeagueDao>(self.conn));
>    |                                         ^^^^^^ the trait `diesel::Expression` is not implemented for `diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>`
>    |
>    = note: required because of the requirements on the impl of `diesel::Expression` for `&diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>`
>    = note: required because of the requirements on the impl of `diesel::query_dsl::filter_dsl::FilterDsl<&diesel_full_text_search::dsl::predicates::Matches<diesel_full_text_search::to_tsvector_t<diesel::expression::bound::Bound<diesel::types::Text, &str>>, &diesel_full_text_search::to_tsquery_t<diesel::expression::bound::Bound<diesel::types::Text, std::string::String>>>>` for `diesel::query_builder::SelectStatement<schema::league::table>`
> ```

how did you using the diesel full text search, could you paste a simple demo? this is how I am trying to do: https://stackoverflow.com/questions/73045948/cannot-infer-type-for-type-parameter-t-declared-on-the-associated-function-ma

**Comment by weiznich** [comment]
@jiangxiaoqiang This is really the last warning. Please do not post to old closed issues to ask questions about your problems. This is really not the right place to ask such questions, as our issue tracker is never the right place to ask for support. The next time I see this happen I will block you from the diesel organization.
