### ISSUE TITLE
the trait `NonAggregate` is not implemented for `char`

### ISSUE THREAD

**Issue by jiangxiaoqiang** [diesel-rs/diesel_full_text_search#31]
when I using this code to do a full text search:

```
#[macro_use]
extern crate diesel;

use diesel::{QueryDsl, RunQueryDsl};
use diesel_full_text_search::{plainto_tsquery, to_tsvector};
use rust_wheel::config::db::config;
use diesel_full_text_search::TsVectorExtensions;
use crate::model::diesel::dict::dict_models::Article;

mod model;

fn main() {
    use model::diesel::dict::dict_schema::article as article_table;
    let connection = config::establish_connection();
    let mut query = article_table::table.into_boxed::<diesel::pg::Pg>();
    let tsvector = to_tsvector("'dolphinzhcfg', title");
    let a: char = char::from_u32(0xDE01).unwrap();;
    query = query.filter(&tsvector.matches(a));
    let query_result = query.load::<Article>(&connection);
}
```

shows error:

```
error[E0277]: the trait bound `char: QueryFragment<Pg>` is not satisfied
  --> src/main.rs:18:19
   |
18 |     query = query.filter(&tsvector.matches(a));
   |                   ^^^^^^ the trait `QueryFragment<Pg>` is not implemented for `char`
   |
   = help: the following other types implement trait `QueryFragment<DB>`:
             <&'a T as QueryFragment<DB>>
             <() as QueryFragment<DB>>
             <(A, B) as QueryFragment<__DB>>
             <(A, B, C) as QueryFragment<__DB>>
             <(A, B, C, D) as QueryFragment<__DB>>
             <(A, B, C, D, E) as QueryFragment<__DB>>
             <(A, B, C, D, E, F) as QueryFragment<__DB>>
             <(A, B, C, D, E, F, G) as QueryFragment<__DB>>
           and 186 others
   = note: required because of the requirements on the impl of `QueryFragment<Pg>` for `diesel_full_text_search::dsl::predicates::Matches<to_tsvector_t<diesel::expression::bound::Bound<Text, &str>>, char>`
   = note: 1 redundant requirement hidden
   = note: required because of the requirements on the impl of `QueryFragment<Pg>` for `&diesel_full_text_search::dsl::predicates::Matches<to_tsvector_t<diesel::expression::bound::Bound<Text, &str>>, char>`
   = note: required because of the requirements on the impl of `query_builder::where_clause::WhereAnd<&diesel_full_text_search::dsl::predicates::Matches<to_tsvector_t<diesel::expression::bound::Bound<Text, &str>>, char>>` for `query_builder::where_clause::BoxedWhereClause<'_, Pg>`
   = note: required because of the requirements on the impl of `FilterDsl<&diesel_full_text_search::dsl::predicates::Matches<to_tsvector_t<diesel::expression::bound::Bound<Text, &str>>, char>>` for `diesel::query_builder::BoxedSelectStatement<'_, (BigInt, BigInt, Text, Text, Text, BigInt, BigInt, diesel::sql_types::Nullable<Text>, BigInt, diesel::sql_types::Nullable<Text>, Integer, diesel::sql_types::Nullable<Integer>), table, Pg>`

For more information about this error, try `rustc --explain E0277`.
warning: `rust-learn` (bin "rust-learn") generated 2 warnings

```

this is the `dict_schema.rs`:

    table! {
        article (id) {
            id -> Int8,
            user_id -> Int8,
            title -> Varchar,
            author -> Varchar,
            guid -> Varchar,
            created_time -> Int8,
            updated_time -> Int8,
            link -> Nullable<Varchar>,
            sub_source_id -> Int8,
            cover_image -> Nullable<Varchar>,
            channel_reputation -> Int4,
            editor_pick -> Nullable<Int4>,
        }
    }

and this is the `dict_models.rs`:

    // Generated by diesel_ext
    
    #![allow(unused)]
    #![allow(clippy::all)]
    
    use std::io::Write;
    use diesel::deserialize::FromSql;
    use diesel::pg::Pg;
    use diesel::serialize::{Output, ToSql};
    use diesel::sql_types::Jsonb;
    use rocket::serde::Serialize;
    use serde::Deserialize;
    use chrono::DateTime;
    use chrono::Utc;
    use crate::model::diesel::dict::dict_schema::*;
    
    #[derive(Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
    #[table_name = "article"]
    pub struct Article {
        pub id: i64,
        pub user_id: i64,
        pub title: String,
        pub author: String,
        pub guid: String,
        pub created_time: i64,
        pub updated_time: i64,
        pub link: Option<String>,
        pub sub_source_id: i64,
        pub cover_image: Option<String>,
        pub channel_reputation: i32,
        pub editor_pick: Option<i32>,
    }

this is the dependencies of the demo:

    [package]
    name = "rust-learn"
    version = "0.1.0"
    edition = "2018"
    
    [dependencies]
    rocket = { version = "=0.5.0-rc.2", features = ["json"] }
    
    serde = { version = "1.0.64", features = ["derive"] }
    serde_json = "1.0.64"
    serde_derive = "1.0"
    # database
    diesel = { version = "1.4.7", features = ["postgres","serde_json"] }
    dotenv = "0.15.0"
    jsonwebtoken = "7"
    chrono = "0.4"
    config = "0.11"
    ring = "0.16.20"
    md5 = "0.7.0"
    data-encoding = "2.3.2"
    bigdecimal = "0.3.0"
    # reddwarf public component
    rust_wheel = { git = "https://github.com/jiangxiaoqiang/rust_wheel.git" }
    diesel_full_text_search = "1.0.1"

Am I missing something?

**Comment by weiznich** [comment]
This is expected as `char` is no supported type at this position. Closed as this is not an issue.
To add this here as well: Repeatedly asking the essentially the same question again will not get you any answer faster. It only leads to relevant persons being annoyed of having to deal with multiple notifications about essentially the same thing. This is the best way to just not get any helpful answer at all.
