### ISSUE TITLE
is there any demo to show hot to use to_tsquery_with_search_config

### ISSUE THREAD

**Issue by jiangxiaoqiang** [diesel-rs/diesel_full_text_search#34]
is there any demo to show how to use to_tsquery_with_search_config?

**Comment by weiznich** [comment]
Closed as duplicate of #1

**Comment by jiangxiaoqiang** [comment]
could you help me to write the full text search? I am tried to use this lib to do the full text search, now I facing this problem: https://stackoverflow.com/questions/73061280/the-trait-dieselexpressionexpression-is-not-implemented-for-regconfig  after I complete this task, I promise to add the using exmaple for this repo. @weiznich I have tried to read the source code but it seem hard for me to understand right now.
